-- 删除products表的外键约束
SET FOREIGN_KEY_CHECKS = 0;

-- 检查外键约束
SELECT
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    REFERENCED_TABLE_SCHEMA = 'songjia_textile'
    AND TABLE_NAME = 'products'
    AND REFERENCED_TABLE_NAME IS NOT NULL;

-- 如果有外键约束，则删除
-- 注意：由于我们不知道具体的约束名称，需要先查看约束名称
-- ALTER TABLE products DROP FOREIGN KEY fk_constraint_name;

-- 检查是否还有其他外键约束
SELECT
    CONSTRAINT_NAME,
    TABLE_NAME
FROM
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE
    CONSTRAINT_SCHEMA = 'songjia_textile'
    AND CONSTRAINT_TYPE = 'FOREIGN KEY';

SET FOREIGN_KEY_CHECKS = 1;